### ISSUE TITLE
Incorrect go-import content when git branch is specified

### ISSUE THREAD

**Issue by maverickwoo** [gopherpit/gopherpit#2]
I have set up an example on gopherpit.com to demonstrate the problem.

1. The actual repo https://gitlab.com/maverickwoo/test-gopherpit has a branch named `0.1.0`.

2. With my account at gopherpit.com, I have setup `maverickwoo.gopherpit.com/test-gopherpit` to point to https://gitlab.com/maverickwoo/test-gopherpit with options Git, Branch,`0.1.0`.

3. I can see on https://gopherpit.com/domain/maverickwoo.gopherpit.com that the Path `/test-gopherpit` points to the Repository `https://gitlab.com/maverickwoo/test-gopherpit@branch:0.1.0`.

4. However, the resulting link https://maverickwoo.gopherpit.com/test-gopherpit?go-get=1 currently shows `maverickwoo.gopherpit.com/test-gopherpit git http://maverickwoo.gopherpit.com/test-gopherpit` as the `content` for `go-import`.

P.S. If I do not specify a git branch (i.e., leave it at Master), then the `content` is correct. This explains the title of the issue.

**Comment by janos** [comment]
The difference in package path that you noticed is required for branch/tag change feature. Go get tool is always cloning the master branch and in order to change the git info refs to a different branch or tag, a different git clone URL must be set, like in the point 4. that you noticed. GopherPit is changing the master git ref to the one from the specified branch or tag.

However, there was a bug with git upload pack redirection for repository URLs that do not end with `.git`. It has been fixed, and now `go get -v maverickwoo.gopherpit.com/test-gopherpit` works as expected. The `0.1.0` branch will be cloned into `$(go env GOPATH)/src/maverickwoo.gopherpit.com/test-gopherpit` directory.

**Comment by maverickwoo** [comment]
Thank you very much for the explanation as well as gopherpit overall. I think I now understand why the `content` field is what it is.

However, I have just tried `go get -v maverickwoo.gopherpit.com/test-gopherpit` on my computer and it is not working (output below). Is it possible that perhaps gopherpit.com needs to be restarted?

Thanks again!

Configuration:
```
$ go version
go version go1.8 darwin/amd64
$ git --version
git version 2.12.0
```

Output:
```
$ go get -v maverickwoo.gopherpit.com/test-gopherpit
Fetching https://maverickwoo.gopherpit.com/test-gopherpit?go-get=1
Parsing meta tags from https://maverickwoo.gopherpit.com/test-gopherpit?go-get=1 (status code 200)
get "maverickwoo.gopherpit.com/test-gopherpit": found meta tag main.metaImport{Prefix:"maverickwoo.gopherpit.com/test-gopherpit", VCS:"git", RepoRoot:"https://maverickwoo.gopherpit.com/test-gopherpit"} at https://maverickwoo.gopherpit.com/test-gopherpit?go-get=1
maverickwoo.gopherpit.com/test-gopherpit (download)
# cd .; git clone https://maverickwoo.gopherpit.com/test-gopherpit /Users/maverick/go-landing/src/maverickwoo.gopherpit.com/test-gopherpit
Cloning into '/Users/maverick/go-landing/src/maverickwoo.gopherpit.com/test-gopherpit'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package maverickwoo.gopherpit.com/test-gopherpit: exit status 128
```

**Comment by janos** [comment]
Hi, thank you for detailed explanation. It appears that [this](https://github.com/git/git/commit/50d3413740d1da599cdc0106e6e916741394cc98) change in the latest git release made HTTP redirects disabled by default, but the option http.followRedirects was added.

I have implemented the solution not to redirect, but to proxy git-upload-pack data, which should fix the issue for all git versions.
